# Generated by Django 5.2.15 on 2026-07-08 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("produits_stocks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "po_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="N° Bon de commande"
                    ),
                ),
                (
                    "supplier_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence fournisseur"
                    ),
                ),
                (
                    "order_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date commande"
                    ),
                ),
                (
                    "expected_delivery_date",
                    models.DateField(verbose_name="Date livraison prévue"),
                ),
                (
                    "actual_delivery_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date livraison réelle"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Sous-total",
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Pourcentage"),
                            ("amount", "Montant fixe"),
                        ],
                        default="amount",
                        max_length=10,
                        verbose_name="Type de remise",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Valeur de la remise",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Montant de la remise",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Taux TVA (%)",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Montant TVA",
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Frais de livraison",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="Total"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("sent", "Envoyé"),
                            ("confirmed", "Confirmé"),
                            ("partial", "Partiellement reçu"),
                            ("received", "Reçu"),
                            ("cancelled", "Annulé"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "internal_notes",
                    models.TextField(blank=True, verbose_name="Notes internes"),
                ),
                (
                    "shipping_address",
                    models.TextField(blank=True, verbose_name="Adresse de livraison"),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="N° de suivi"
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="qrcodes/purchase_orders/",
                        verbose_name="QR Code",
                    ),
                ),
                (
                    "qr_code_data",
                    models.TextField(blank=True, verbose_name="Données QR Code"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date approbation"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approuvé par",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bon de commande",
                "verbose_name_plural": "Bons de commande",
                "ordering": ["-order_date"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantité commandée")),
                (
                    "quantity_received",
                    models.IntegerField(default=0, verbose_name="Quantité reçue"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix unitaire"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Remise",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="TVA (%)",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Total ligne"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produits_stocks.product",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="achats_fournisseurs.purchaseorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de commande",
                "verbose_name_plural": "Lignes de commande",
            },
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="N° de réception"
                    ),
                ),
                (
                    "receipt_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de réception"
                    ),
                ),
                ("expected_date", models.DateField(verbose_name="Date prévue")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("in_progress", "En cours"),
                            ("completed", "Terminée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "delivery_note",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="N° Bon de livraison"
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="N° Facture"
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="qrcodes/receipts/",
                        verbose_name="QR Code",
                    ),
                ),
                (
                    "qr_code_data",
                    models.TextField(blank=True, verbose_name="Données QR Code"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Réceptionné par",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="achats_fournisseurs.purchaseorder",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="produits_stocks.warehouse",
                        verbose_name="Entrepôt de destination",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réception",
                "verbose_name_plural": "Réceptions",
                "ordering": ["-receipt_date"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "return_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="N° de retour"
                    ),
                ),
                (
                    "return_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de retour"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("defective", "Produit défectueux"),
                            ("wrong_product", "Produit incorrect"),
                            ("expired", "Produit expiré"),
                            ("damaged", "Produit endommagé"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Raison",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Demandé"),
                            ("approved", "Approuvé"),
                            ("shipped", "Expédié"),
                            ("refunded", "Remboursé"),
                            ("replaced", "Remplacé"),
                            ("rejected", "Refusé"),
                        ],
                        default="requested",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="qrcodes/purchase_returns/",
                        verbose_name="QR Code",
                    ),
                ),
                (
                    "qr_code_data",
                    models.TextField(blank=True, verbose_name="Données QR Code"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="returns",
                        to="achats_fournisseurs.purchaseorder",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="returns",
                        to="achats_fournisseurs.receipt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Retour fournisseur",
                "verbose_name_plural": "Retours fournisseurs",
                "ordering": ["-return_date"],
            },
        ),
        migrations.CreateModel(
            name="ReceiptLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_ordered",
                    models.IntegerField(verbose_name="Quantité commandée"),
                ),
                (
                    "quantity_received",
                    models.IntegerField(verbose_name="Quantité reçue"),
                ),
                (
                    "quantity_damaged",
                    models.IntegerField(default=0, verbose_name="Quantité endommagée"),
                ),
                (
                    "lot_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Numéro de lot"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'expiration"
                    ),
                ),
                (
                    "manufacturing_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de fabrication"
                    ),
                ),
                (
                    "is_quality_checked",
                    models.BooleanField(
                        default=False, verbose_name="Contrôle qualité effectué"
                    ),
                ),
                (
                    "quality_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("passed", "Approuvé"),
                            ("failed", "Refusé"),
                            ("pending", "En attente"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "quality_notes",
                    models.TextField(blank=True, verbose_name="Notes qualité"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="produits_stocks.lot",
                        verbose_name="Lot associé",
                    ),
                ),
                (
                    "po_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt_lines",
                        to="achats_fournisseurs.purchaseorderline",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produits_stocks.product",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="achats_fournisseurs.receipt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de réception",
                "verbose_name_plural": "Lignes de réception",
            },
        ),
        migrations.CreateModel(
            name="PurchaseReturnLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantité retournée")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix unitaire"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Total"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produits_stocks.product",
                    ),
                ),
                (
                    "purchase_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="achats_fournisseurs.purchasereturn",
                    ),
                ),
                (
                    "receipt_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_lines",
                        to="achats_fournisseurs.receiptline",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Code fournisseur"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nom / Raison sociale"
                    ),
                ),
                (
                    "commercial_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nom commercial"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("international", "International"),
                            ("importateur", "Importateur"),
                            ("distributeur", "Distributeur"),
                            ("fabricant", "Fabricant"),
                        ],
                        default="local",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Personne de contact"
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Téléphone")),
                (
                    "mobile",
                    models.CharField(blank=True, max_length=20, verbose_name="Mobile"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("website", models.URLField(blank=True, verbose_name="Site web")),
                ("address", models.TextField(verbose_name="Adresse")),
                ("city", models.CharField(max_length=100, verbose_name="Ville")),
                (
                    "country",
                    models.CharField(
                        default="Sénégal", max_length=100, verbose_name="Pays"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Code postal"
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="N° Identification fiscale",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="N° Registre de commerce",
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        choices=[
                            ("cash", "Comptant"),
                            ("15", "15 jours"),
                            ("30", "30 jours"),
                            ("45", "45 jours"),
                            ("60", "60 jours"),
                            ("90", "90 jours"),
                        ],
                        default="30",
                        max_length=20,
                        verbose_name="Délai de paiement",
                    ),
                ),
                (
                    "delivery_lead_time",
                    models.IntegerField(
                        default=7,
                        help_text="Délai de livraison en jours",
                        verbose_name="Délai de livraison (jours)",
                    ),
                ),
                (
                    "minimum_order",
                    models.IntegerField(default=0, verbose_name="Commande minimum"),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        verbose_name="Note (0-5)",
                    ),
                ),
                (
                    "total_purchases",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Total achats",
                    ),
                ),
                (
                    "total_orders",
                    models.IntegerField(default=0, verbose_name="Nombre de commandes"),
                ),
                (
                    "on_time_delivery_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Taux livraison à temps (%)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "is_preferred",
                    models.BooleanField(
                        default=False, verbose_name="Fournisseur privilégié"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date modification"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fournisseur",
                "verbose_name_plural": "Fournisseurs",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_orders",
                to="achats_fournisseurs.supplier",
            ),
        ),
        migrations.CreateModel(
            name="SupplierContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom complet")),
                (
                    "position",
                    models.CharField(blank=True, max_length=100, verbose_name="Poste"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Téléphone")),
                (
                    "mobile",
                    models.CharField(blank=True, max_length=20, verbose_name="Mobile"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, verbose_name="Contact principal"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="achats_fournisseurs.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact fournisseur",
                "verbose_name_plural": "Contacts fournisseurs",
            },
        ),
        migrations.CreateModel(
            name="SupplierInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="N° Facture"
                    ),
                ),
                ("invoice_date", models.DateField(verbose_name="Date facture")),
                ("due_date", models.DateField(verbose_name="Date d'échéance")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant"
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="TVA"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total"
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Montant payé",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Reçue"),
                            ("verified", "Vérifiée"),
                            ("paid", "Payée"),
                            ("partial", "Partiellement payée"),
                            ("disputed", "Contestée"),
                        ],
                        default="received",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de paiement"
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence paiement"
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="invoices/",
                        verbose_name="PDF facture",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="achats_fournisseurs.purchaseorder",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="achats_fournisseurs.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture fournisseur",
                "verbose_name_plural": "Factures fournisseurs",
                "ordering": ["-invoice_date"],
            },
        ),
        migrations.CreateModel(
            name="SupplierProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier_sku",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence fournisseur"
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix d'achat"
                    ),
                ),
                (
                    "lead_time",
                    models.IntegerField(
                        default=7, verbose_name="Délai de livraison (jours)"
                    ),
                ),
                (
                    "minimum_order",
                    models.IntegerField(default=1, verbose_name="Quantité minimum"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suppliers",
                        to="produits_stocks.product",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="achats_fournisseurs.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produit fournisseur",
                "verbose_name_plural": "Produits fournisseurs",
                "unique_together": {("supplier", "product")},
            },
        ),
    ]
