# Generated by Django 5.2.15 on 2026-07-08 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("produits_stocks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Taxe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Taux (%)"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Par défaut"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Taxe",
                "verbose_name_plural": "Taxes",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Code client"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nom / Raison sociale"
                    ),
                ),
                (
                    "commercial_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nom commercial"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("particulier", "Particulier"),
                            ("entreprise", "Entreprise"),
                            ("revendeur", "Revendeur"),
                            ("grossiste", "Grossiste"),
                        ],
                        default="particulier",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Personne de contact"
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Téléphone")),
                (
                    "mobile",
                    models.CharField(blank=True, max_length=20, verbose_name="Mobile"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("website", models.URLField(blank=True, verbose_name="Site web")),
                ("address", models.TextField(verbose_name="Adresse")),
                ("city", models.CharField(max_length=100, verbose_name="Ville")),
                (
                    "country",
                    models.CharField(
                        default="Sénégal", max_length=100, verbose_name="Pays"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Code postal"
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="N° Identification fiscale",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="N° Registre de commerce",
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        choices=[
                            ("cash", "Comptant"),
                            ("15", "15 jours"),
                            ("30", "30 jours"),
                            ("45", "45 jours"),
                            ("60", "60 jours"),
                        ],
                        default="cash",
                        max_length=20,
                        verbose_name="Délai de paiement",
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Limite de crédit",
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Solde actuel",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        verbose_name="Note (0-5)",
                    ),
                ),
                (
                    "total_purchases",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Total achats",
                    ),
                ),
                (
                    "total_orders",
                    models.IntegerField(default=0, verbose_name="Nombre de commandes"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("inactif", "Inactif"),
                            ("bloque", "Bloqué"),
                        ],
                        default="actif",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "is_favorite",
                    models.BooleanField(default=False, verbose_name="Client favori"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date modification"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Facture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="N° Facture"
                    ),
                ),
                (
                    "invoice_date",
                    models.DateField(auto_now_add=True, verbose_name="Date facture"),
                ),
                ("due_date", models.DateField(verbose_name="Date échéance")),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Sous-total",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="TVA"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="Total"
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Montant payé",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("sent", "Envoyée"),
                            ("paid", "Payée"),
                            ("overdue", "En retard"),
                            ("cancelled", "Annulée"),
                            ("partial", "Partiellement payée"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="invoices/",
                        verbose_name="PDF facture",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="qrcodes/invoices/",
                        verbose_name="QR Code",
                    ),
                ),
                (
                    "qr_code_data",
                    models.TextField(blank=True, verbose_name="Données QR Code"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="ventes_clients.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture",
                "verbose_name_plural": "Factures",
                "ordering": ["-invoice_date"],
            },
        ),
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Espèces"),
                            ("card", "Carte bancaire"),
                            ("check", "Chèque"),
                            ("transfer", "Virement"),
                            ("mobile_money", "Mobile Money"),
                            ("credit", "Crédit"),
                        ],
                        max_length=20,
                        verbose_name="Méthode",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence"
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date paiement"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="qrcodes/payments/",
                        verbose_name="QR Code",
                    ),
                ),
                (
                    "qr_code_data",
                    models.TextField(blank=True, verbose_name="Données QR Code"),
                ),
                (
                    "facture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements",
                        to="ventes_clients.facture",
                        verbose_name="Facture",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reçu par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="PointDeVente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="produits_stocks.warehouse",
                        verbose_name="Entrepôt associé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Point de vente",
                "verbose_name_plural": "Points de vente",
            },
        ),
        migrations.CreateModel(
            name="Remise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("percentage", "Pourcentage"),
                            ("amount", "Montant fixe"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valeur"
                    ),
                ),
                (
                    "min_purchase",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Achat minimum",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Date début"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Date fin"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clients",
                    models.ManyToManyField(
                        blank=True,
                        to="ventes_clients.client",
                        verbose_name="Clients concernés",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remise",
                "verbose_name_plural": "Remises",
            },
        ),
        migrations.CreateModel(
            name="SessionCaisse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opening_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date ouverture"
                    ),
                ),
                (
                    "closing_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date fermeture"
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Solde d'ouverture",
                    ),
                ),
                (
                    "closing_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Solde de fermeture",
                    ),
                ),
                (
                    "expected_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Solde attendu",
                    ),
                ),
                (
                    "difference",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Différence",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Ouverte"),
                            ("closed", "Fermée"),
                            ("suspended", "Suspendue"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "point_de_vente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="ventes_clients.pointdevente",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Session de caisse",
                "verbose_name_plural": "Sessions de caisse",
                "ordering": ["-opening_date"],
            },
        ),
        migrations.CreateModel(
            name="MouvementCaisse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("sale", "Vente"),
                            ("payment", "Paiement"),
                            ("deposit", "Dépôt"),
                            ("withdrawal", "Retrait"),
                            ("expense", "Dépense"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Description"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="ventes_clients.sessioncaisse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mouvement de caisse",
                "verbose_name_plural": "Mouvements de caisse",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Vente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="N° Facture"
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="N° Commande",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=200, verbose_name="Nom client"),
                ),
                (
                    "client_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone client"
                    ),
                ),
                (
                    "client_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email client"
                    ),
                ),
                (
                    "client_address",
                    models.TextField(blank=True, verbose_name="Adresse client"),
                ),
                (
                    "sale_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date vente"),
                ),
                (
                    "delivery_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date livraison"
                    ),
                ),
                (
                    "payment_due_date",
                    models.DateField(verbose_name="Date échéance paiement"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Sous-total",
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percentage", "Pourcentage"), ("amount", "Montant")],
                        default="percentage",
                        max_length=20,
                        verbose_name="Type remise",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Valeur remise",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Montant remise",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Taux TVA (%)",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Montant TVA",
                    ),
                ),
                (
                    "shipping_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Frais de livraison",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total TTC",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Méthode de paiement"
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("partial", "Paiement partiel"),
                            ("paid", "Payé"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut paiement",
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Montant payé",
                    ),
                ),
                (
                    "amount_due",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Montant dû",
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Méthode de livraison"
                    ),
                ),
                (
                    "delivery_address",
                    models.TextField(
                        blank=True, null=True, verbose_name="Adresse de livraison"
                    ),
                ),
                (
                    "delivery_status",
                    models.CharField(
                        default="pending",
                        max_length=50,
                        verbose_name="Statut livraison",
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="N° de suivi"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("confirmed", "Confirmée"),
                            ("paid", "Payée"),
                            ("delivered", "Livrée"),
                            ("cancelled", "Annulée"),
                            ("returned", "Retournée"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "internal_notes",
                    models.TextField(blank=True, verbose_name="Notes internes"),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="qrcodes/sales/",
                        verbose_name="QR Code",
                    ),
                ),
                (
                    "qr_code_data",
                    models.TextField(blank=True, verbose_name="Données QR Code"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date modification"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales",
                        to="ventes_clients.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vente",
                "verbose_name_plural": "Ventes",
                "ordering": ["-sale_date"],
            },
        ),
        migrations.CreateModel(
            name="LigneVente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantité")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix unitaire"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Remise",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="TVA (%)",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Total ligne"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="produits_stocks.lot",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produits_stocks.product",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="ventes_clients.vente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de vente",
                "verbose_name_plural": "Lignes de vente",
            },
        ),
        migrations.AddField(
            model_name="facture",
            name="sale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="ventes_clients.vente",
            ),
        ),
        migrations.CreateModel(
            name="Avoir",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avoir_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="N° Avoir"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("credit", "Avoir"), ("debit", "Note de débit")],
                        default="credit",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant"
                    ),
                ),
                ("reason", models.TextField(verbose_name="Raison")),
                ("date", models.DateField(auto_now_add=True, verbose_name="Date")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="ventes_clients.client",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="ventes_clients.vente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avoir",
                "verbose_name_plural": "Avoirs",
                "ordering": ["-date"],
            },
        ),
    ]
