# Generated by Django 5.2.15 on 2026-07-19 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produits_stocks", "0001_initial"),
        ("ventes_clients", "0002_devis_lignedevis"),
    ]

    operations = [
        migrations.AddField(
            model_name="devis",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devis",
                to="produits_stocks.warehouse",
                verbose_name="Entrepôt",
            ),
        ),
        migrations.AddField(
            model_name="vente",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ventes",
                to="produits_stocks.warehouse",
                verbose_name="Entrepôt de vente",
            ),
        ),
    ]
