# Generated by Django 5.2.15 on 2026-07-19 11:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ventes_clients", "0003_devis_warehouse_vente_warehouse"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pointdevente",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="pointdevente",
            name="warehouse",
        ),
        migrations.RemoveField(
            model_name="sessioncaisse",
            name="point_de_vente",
        ),
        migrations.RemoveField(
            model_name="sessioncaisse",
            name="user",
        ),
        migrations.DeleteModel(
            name="MouvementCaisse",
        ),
        migrations.DeleteModel(
            name="PointDeVente",
        ),
        migrations.DeleteModel(
            name="SessionCaisse",
        ),
    ]
