# Generated by Django 5.2.15 on 2026-07-19 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ventes_clients", "0004_remove_pointdevente_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devis",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devis",
                to="ventes_clients.client",
            ),
        ),
        migrations.AlterField(
            model_name="vente",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to="ventes_clients.client",
            ),
        ),
    ]
