# Generated by Django 5.2.15 on 2026-07-19 16:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produits_stocks", "0001_initial"),
        ("ventes_clients", "0005_alter_devis_client_alter_vente_client"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="paiement",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="avoir",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="avoir",
            name="avoir_number",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="avoir",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credits",
                to="ventes_clients.client",
            ),
        ),
        migrations.AlterField(
            model_name="avoir",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="avoir",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="avoir",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="avoir",
            name="reason",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="avoir",
            name="type",
            field=models.CharField(
                choices=[("credit", "Avoir"), ("debit", "Note de débit")],
                default="credit",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="address",
            field=models.TextField(blank=True, verbose_name="Adresse"),
        ),
        migrations.AlterField(
            model_name="client",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Ville"),
        ),
        migrations.AlterField(
            model_name="client",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clients_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="client",
            name="rating",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=3,
                verbose_name="Note",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="total_orders",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Nombre de commandes"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="devis",
            name="client_address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="devis",
            name="client_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="devis",
            name="client_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Nom client"
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="client_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="devis",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="devis",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devis_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="devis_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="devis",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="discount_type",
            field=models.CharField(
                choices=[("percentage", "Pourcentage"), ("amount", "Montant")],
                default="percentage",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="discount_value",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="internal_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="devis",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="devis",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qrcodes/devis/"),
        ),
        migrations.AlterField(
            model_name="devis",
            name="qr_code_data",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="devis",
            name="shipping_fee",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("sent", "Envoyé"),
                    ("accepted", "Accepté"),
                    ("refused", "Refusé"),
                    ("expired", "Expiré"),
                    ("converted", "Converti en vente"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="total",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="devis",
            name="valid_until",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="devis",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devis",
                to="produits_stocks.warehouse",
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="ventes_clients.client",
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="due_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="facture",
            name="invoice_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="facture",
            name="invoice_number",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="facture",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="facture",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="invoices/"),
        ),
        migrations.AlterField(
            model_name="facture",
            name="qr_code",
            field=models.ImageField(
                blank=True, null=True, upload_to="qrcodes/invoices/"
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="qr_code_data",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="facture",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("sent", "Envoyée"),
                    ("paid", "Payée"),
                    ("overdue", "En retard"),
                    ("cancelled", "Annulée"),
                    ("partial", "Partiellement payée"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="total",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="lignedevis",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="lignedevis",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="lignedevis",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="produits_stocks.product",
            ),
        ),
        migrations.AlterField(
            model_name="lignedevis",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="lignedevis",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="lignedevis",
            name="total",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="lignedevis",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="lignevente",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="lignevente",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="lignevente",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="produits_stocks.product",
            ),
        ),
        migrations.AlterField(
            model_name="lignevente",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="Quantité"),
        ),
        migrations.AlterField(
            model_name="lignevente",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="lignevente",
            name="total",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="lignevente",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="paiement",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="paiement",
            name="facture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paiements",
                to="ventes_clients.facture",
            ),
        ),
        migrations.AlterField(
            model_name="paiement",
            name="method",
            field=models.CharField(
                choices=[
                    ("cash", "Espèces"),
                    ("card", "Carte bancaire"),
                    ("check", "Chèque"),
                    ("transfer", "Virement"),
                    ("mobile_money", "Mobile Money"),
                    ("credit", "Crédit"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="paiement",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="paiement",
            name="payment_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="paiement",
            name="qr_code",
            field=models.ImageField(
                blank=True, null=True, upload_to="qrcodes/payments/"
            ),
        ),
        migrations.AlterField(
            model_name="paiement",
            name="qr_code_data",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="paiement",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="paiement",
            name="reference",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="remise",
            name="clients",
            field=models.ManyToManyField(blank=True, to="ventes_clients.client"),
        ),
        migrations.AlterField(
            model_name="remise",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="remise",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="remise",
            name="min_purchase",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="remise",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="remise",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="remise",
            name="type",
            field=models.CharField(
                choices=[("percentage", "Pourcentage"), ("amount", "Montant fixe")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="remise",
            name="value",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="taxe",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="taxe",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="taxe",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="taxe",
            name="rate",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="vente",
            name="amount_due",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="vente",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="vente",
            name="client_address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="vente",
            name="client_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="vente",
            name="client_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="vente",
            name="client_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="vente",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="vente",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="vente",
            name="delivery_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vente",
            name="delivery_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vente",
            name="delivery_method",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="vente",
            name="delivery_status",
            field=models.CharField(default="pending", max_length=50),
        ),
        migrations.AlterField(
            model_name="vente",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="vente",
            name="discount_type",
            field=models.CharField(
                choices=[("percentage", "Pourcentage"), ("amount", "Montant")],
                default="percentage",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vente",
            name="discount_value",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="vente",
            name="internal_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="vente",
            name="invoice_number",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="vente",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="vente",
            name="order_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="vente",
            name="payment_due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vente",
            name="payment_method",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="vente",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("partial", "Paiement partiel"),
                    ("paid", "Payé"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vente",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qrcodes/sales/"),
        ),
        migrations.AlterField(
            model_name="vente",
            name="qr_code_data",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="vente",
            name="sale_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="vente",
            name="shipping_fee",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="vente",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("confirmed", "Confirmée"),
                    ("paid", "Payée"),
                    ("delivered", "Livrée"),
                    ("cancelled", "Annulée"),
                    ("returned", "Retournée"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vente",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="vente",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="vente",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="vente",
            name="total",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="vente",
            name="tracking_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="vente",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="vente",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ventes",
                to="produits_stocks.warehouse",
            ),
        ),
    ]
