# Generated by Django 5.2.15 on 2026-07-25 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produits_stocks", "0001_initial"),
        ("ventes_clients", "0006_paiement_updated_at_alter_avoir_amount_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="devis",
            name="client_address",
            field=models.TextField(blank=True, verbose_name="Adresse client"),
        ),
        migrations.AlterField(
            model_name="devis",
            name="client_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Email client"
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="client_name",
            field=models.CharField(max_length=200, verbose_name="Nom client"),
        ),
        migrations.AlterField(
            model_name="devis",
            name="client_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Téléphone client"
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date création"),
        ),
        migrations.AlterField(
            model_name="devis",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devis",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="devis_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date devis"),
        ),
        migrations.AlterField(
            model_name="devis",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Montant remise",
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="discount_type",
            field=models.CharField(
                choices=[("percentage", "Pourcentage"), ("amount", "Montant")],
                default="percentage",
                max_length=20,
                verbose_name="Type remise",
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="discount_value",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Valeur remise"
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="internal_notes",
            field=models.TextField(blank=True, verbose_name="Notes internes"),
        ),
        migrations.AlterField(
            model_name="devis",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="devis",
            name="qr_code",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="qrcodes/devis/",
                verbose_name="QR Code",
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="qr_code_data",
            field=models.TextField(blank=True, verbose_name="Données QR Code"),
        ),
        migrations.AlterField(
            model_name="devis",
            name="shipping_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Frais de livraison",
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("sent", "Envoyé"),
                    ("accepted", "Accepté"),
                    ("refused", "Refusé"),
                    ("expired", "Expiré"),
                    ("converted", "Converti en vente"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Sous-total"
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Montant TVA"
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="Taux TVA (%)"
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Total TTC"
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Date modification"),
        ),
        migrations.AlterField(
            model_name="devis",
            name="valid_until",
            field=models.DateField(verbose_name="Valable jusqu'au"),
        ),
        migrations.AlterField(
            model_name="devis",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devis",
                to="produits_stocks.warehouse",
                verbose_name="Entrepôt",
            ),
        ),
    ]
