# Generated by Django 5.2.15 on 2026-07-08 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nom")),
                ("symbol", models.CharField(max_length=10, verbose_name="Symbole")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("unit", "Unité"),
                            ("weight", "Poids"),
                            ("volume", "Volume"),
                            ("length", "Longueur"),
                        ],
                        default="unit",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "conversion_factor",
                    models.DecimalField(
                        decimal_places=4,
                        default=1.0,
                        max_digits=10,
                        verbose_name="Facteur de conversion",
                    ),
                ),
                (
                    "is_base_unit",
                    models.BooleanField(default=False, verbose_name="Unité de base"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Unité de mesure",
                "verbose_name_plural": "Unités de mesure",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("main", "Principal"),
                            ("secondary", "Secondaire"),
                            ("store", "Magasin"),
                            ("warehouse", "Entrepôt"),
                        ],
                        default="warehouse",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("address", models.TextField(verbose_name="Adresse")),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Ville"),
                ),
                (
                    "country",
                    models.CharField(
                        default="Sénégal", max_length=100, verbose_name="Pays"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "manager",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Responsable"
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Capacité maximale"
                    ),
                ),
                (
                    "current_occupancy",
                    models.IntegerField(default=0, verbose_name="Occupation actuelle"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrepôt",
                "verbose_name_plural": "Entrepôts",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Code"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categories/",
                        verbose_name="Image",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date modification"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="produits_stocks.category",
                        verbose_name="Catégorie parente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("start_date", models.DateTimeField(verbose_name="Date début")),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date fin"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planifié"),
                            ("in_progress", "En cours"),
                            ("completed", "Terminé"),
                            ("cancelled", "Annulé"),
                            ("verified", "Vérifié"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "total_expected_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Valeur théorique",
                    ),
                ),
                (
                    "total_actual_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Valeur réelle",
                    ),
                ),
                (
                    "total_difference",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Différence totale",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date création"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_inventories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vérifié par",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventories",
                        to="produits_stocks.warehouse",
                        verbose_name="Entrepôt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventaire",
                "verbose_name_plural": "Inventaires",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Code produit"
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Code-barres",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("consignable", "Consignable"),
                            ("expirable", "À durée limitée"),
                            ("service", "Service"),
                        ],
                        default="standard",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix d'achat"
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix de vente"
                    ),
                ),
                (
                    "wholesale_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Prix de gros",
                    ),
                ),
                (
                    "promo_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Prix promotionnel",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Taux de TVA (%)",
                    ),
                ),
                (
                    "has_expiry",
                    models.BooleanField(
                        default=False, verbose_name="A une date d'expiration"
                    ),
                ),
                (
                    "shelf_life_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Durée de conservation en jours",
                        null=True,
                        verbose_name="Durée de conservation",
                    ),
                ),
                (
                    "alert_days",
                    models.IntegerField(
                        default=30,
                        help_text="Jours avant expiration pour déclencher une alerte",
                        verbose_name="Jours d'alerte",
                    ),
                ),
                (
                    "min_stock",
                    models.IntegerField(default=0, verbose_name="Stock minimum"),
                ),
                (
                    "max_stock",
                    models.IntegerField(default=0, verbose_name="Stock maximum"),
                ),
                (
                    "reorder_point",
                    models.IntegerField(default=0, verbose_name="Point de commande"),
                ),
                (
                    "reorder_quantity",
                    models.IntegerField(
                        default=0, verbose_name="Quantité de réapprovisionnement"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/",
                        verbose_name="Image principale",
                    ),
                ),
                (
                    "gallery",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Galerie d'images"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Actif"),
                            ("inactive", "Inactif"),
                            ("out_of_stock", "Rupture de stock"),
                            ("discontinued", "Abandonné"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Produit vedette"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date modification"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="produits_stocks.category",
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="produits_stocks.unitmeasure",
                        verbose_name="Unité de mesure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produit",
                "verbose_name_plural": "Produits",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Lot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lot_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Numéro de lot"
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Numéro de batch"
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Code-barres",
                    ),
                ),
                (
                    "initial_quantity",
                    models.IntegerField(verbose_name="Quantité initiale"),
                ),
                (
                    "current_quantity",
                    models.IntegerField(verbose_name="Quantité actuelle"),
                ),
                (
                    "reserved_quantity",
                    models.IntegerField(default=0, verbose_name="Quantité réservée"),
                ),
                (
                    "min_quantity_alert",
                    models.IntegerField(
                        default=0, verbose_name="Alerte quantité minimale"
                    ),
                ),
                (
                    "manufacturing_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de fabrication"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'expiration"
                    ),
                ),
                (
                    "reception_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Date de réception"
                    ),
                ),
                (
                    "last_used_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Dernière utilisation"
                    ),
                ),
                (
                    "blocked_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de blocage"
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Prix d'achat unitaire",
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Prix de vente unitaire",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("good", "Bon"),
                            ("expiring", "Expire bientôt"),
                            ("expired", "Expiré"),
                            ("blocked", "Bloqué"),
                            ("quarantine", "En quarantaine"),
                        ],
                        default="good",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "is_blocked",
                    models.BooleanField(default=False, verbose_name="Bloqué"),
                ),
                (
                    "block_reason",
                    models.TextField(blank=True, verbose_name="Raison du blocage"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date création"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lots",
                        to="produits_stocks.product",
                        verbose_name="Produit",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="produits_stocks.unitmeasure",
                        verbose_name="Unité",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lots",
                        to="produits_stocks.warehouse",
                        verbose_name="Entrepôt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lot",
                "verbose_name_plural": "Lots",
                "ordering": ["expiry_date", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference_number", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("in_progress", "En cours"),
                            ("completed", "Terminé"),
                            ("cancelled", "Annulé"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_out",
                        to="produits_stocks.warehouse",
                    ),
                ),
                (
                    "to_warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_in",
                        to="produits_stocks.warehouse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransferItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "destination_lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="produits_stocks.lot",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produits_stocks.product",
                    ),
                ),
                (
                    "source_lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="produits_stocks.lot",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="produits_stocks.transfer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpiryAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Attention"),
                            ("critical", "Critique"),
                            ("emergency", "Urgence"),
                        ],
                        default="warning",
                        max_length=20,
                        verbose_name="Sévérité",
                    ),
                ),
                ("days_left", models.IntegerField(verbose_name="Jours restants")),
                ("message", models.TextField(verbose_name="Message")),
                ("is_read", models.BooleanField(default=False, verbose_name="Lu")),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="Traité"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date traitement"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date création"
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Traité par",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="produits_stocks.lot",
                        verbose_name="Lot",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expiry_alerts",
                        to="produits_stocks.product",
                        verbose_name="Produit",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="produits_stocks.warehouse",
                        verbose_name="Entrepôt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerte d'expiration",
                "verbose_name_plural": "Alertes d'expiration",
                "ordering": ["days_left", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expected_quantity",
                    models.IntegerField(verbose_name="Quantité théorique"),
                ),
                (
                    "actual_quantity",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Quantité réelle"
                    ),
                ),
                (
                    "difference",
                    models.IntegerField(default=0, verbose_name="Différence"),
                ),
                (
                    "expected_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Valeur théorique",
                    ),
                ),
                (
                    "actual_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Valeur réelle",
                    ),
                ),
                (
                    "value_difference",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Différence valeur",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Vérifié"),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date vérification"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="produits_stocks.inventory",
                        verbose_name="Inventaire",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vérifié par",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="produits_stocks.lot",
                        verbose_name="Lot",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produits_stocks.product",
                        verbose_name="Produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne d'inventaire",
                "verbose_name_plural": "Lignes d'inventaire",
                "unique_together": {("inventory", "product", "lot")},
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("purchase_in", "Entrée par achat"),
                            ("sale_out", "Sortie par vente"),
                            ("transfer_in", "Entrée par transfert"),
                            ("transfer_out", "Sortie par transfert"),
                            ("adjustment_plus", "Ajustement (+)"),
                            ("adjustment_minus", "Ajustement (-)"),
                            ("return_in", "Entrée par retour"),
                            ("return_out", "Sortie par retour"),
                            ("expired_out", "Sortie par expiration"),
                            ("damaged_out", "Sortie par perte/dommage"),
                            ("inventory_adjustment", "Ajustement inventaire"),
                        ],
                        max_length=30,
                        verbose_name="Type de mouvement",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantité")),
                (
                    "previous_quantity",
                    models.IntegerField(default=0, verbose_name="Quantité précédente"),
                ),
                (
                    "new_quantity",
                    models.IntegerField(default=0, verbose_name="Nouvelle quantité"),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Type de référence"
                    ),
                ),
                (
                    "reference_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID de référence"
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Numéro de référence"
                    ),
                ),
                (
                    "reason",
                    models.CharField(blank=True, max_length=200, verbose_name="Raison"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements",
                        to="produits_stocks.lot",
                        verbose_name="Lot",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="produits_stocks.product",
                        verbose_name="Produit",
                    ),
                ),
                (
                    "from_warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements_out",
                        to="produits_stocks.warehouse",
                        verbose_name="Entrepôt source",
                    ),
                ),
                (
                    "to_warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements_in",
                        to="produits_stocks.warehouse",
                        verbose_name="Entrepôt destination",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mouvement de stock",
                "verbose_name_plural": "Mouvements de stock",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "created_at"],
                        name="produits_st_product_e6fbea_idx",
                    ),
                    models.Index(
                        fields=["movement_type"], name="produits_st_movemen_4dfa3b_idx"
                    ),
                    models.Index(
                        fields=["reference_type", "reference_id"],
                        name="produits_st_referen_38fd31_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(default=0, verbose_name="Quantité totale"),
                ),
                (
                    "reserved_quantity",
                    models.IntegerField(default=0, verbose_name="Quantité réservée"),
                ),
                (
                    "min_stock_override",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Stock minimum (surcharge)"
                    ),
                ),
                (
                    "max_stock_override",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Stock maximum (surcharge)"
                    ),
                ),
                (
                    "last_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="produits_stocks.product",
                        verbose_name="Produit",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="produits_stocks.warehouse",
                        verbose_name="Entrepôt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock",
                "verbose_name_plural": "Stocks",
                "indexes": [
                    models.Index(
                        fields=["product", "warehouse"],
                        name="produits_st_product_fe6534_idx",
                    ),
                    models.Index(
                        fields=["quantity"], name="produits_st_quantit_810b3e_idx"
                    ),
                ],
                "unique_together": {("product", "warehouse")},
            },
        ),
        migrations.AddIndex(
            model_name="lot",
            index=models.Index(
                fields=["product", "expiry_date"], name="produits_st_product_a2eee1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lot",
            index=models.Index(
                fields=["status", "expiry_date"], name="produits_st_status_280eec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lot",
            index=models.Index(
                fields=["lot_number"], name="produits_st_lot_num_78ff9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expiryalert",
            index=models.Index(
                fields=["product", "is_processed"],
                name="produits_st_product_d2d21e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expiryalert",
            index=models.Index(
                fields=["severity", "is_read"], name="produits_st_severit_040d4e_idx"
            ),
        ),
    ]
