# Generated by Django 5.2.15 on 2026-07-25 18:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("achats_fournisseurs", "0001_initial"),
        ("produits_stocks", "0001_initial"),
        ("ventes_clients", "0006_paiement_updated_at_alter_avoir_amount_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Caisse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Code caisse"
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, verbose_name="Nom de la caisse"),
                ),
                (
                    "type_caisse",
                    models.CharField(
                        choices=[
                            ("principale", "Caisse principale"),
                            ("secondaire", "Caisse secondaire"),
                            ("mobile", "Caisse mobile"),
                            ("virtuelle", "Caisse virtuelle"),
                        ],
                        default="principale",
                        max_length=20,
                        verbose_name="Type de caisse",
                    ),
                ),
                (
                    "solde_initial",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Solde initial",
                    ),
                ),
                (
                    "solde_actuel",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Solde actuel",
                    ),
                ),
                (
                    "seuil_min",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Seuil minimum",
                    ),
                ),
                (
                    "seuil_max",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Seuil maximum",
                    ),
                ),
                (
                    "devise",
                    models.CharField(
                        default="XOF", max_length=3, verbose_name="Devise"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="Caisse par défaut"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="caisses_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="caisses_gerrees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="caisses",
                        to="produits_stocks.warehouse",
                        verbose_name="Entrepôt/Magasin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caisse",
                "verbose_name_plural": "Caisses",
                "ordering": ["code"],
                "unique_together": {("warehouse", "code")},
            },
        ),
        migrations.CreateModel(
            name="CompteBancaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banque", models.CharField(max_length=100, verbose_name="Banque")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Code compte"
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom du compte")),
                (
                    "type_compte",
                    models.CharField(
                        choices=[
                            ("courant", "Compte courant"),
                            ("epargne", "Compte épargne"),
                            ("bloque", "Compte bloqué"),
                        ],
                        default="courant",
                        max_length=20,
                        verbose_name="Type de compte",
                    ),
                ),
                (
                    "numero_compte",
                    models.CharField(max_length=50, verbose_name="Numéro de compte"),
                ),
                (
                    "iban",
                    models.CharField(
                        blank=True, max_length=34, null=True, verbose_name="IBAN"
                    ),
                ),
                (
                    "bic",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="BIC/SWIFT"
                    ),
                ),
                (
                    "devise",
                    models.CharField(
                        default="XOF", max_length=3, verbose_name="Devise"
                    ),
                ),
                (
                    "solde_initial",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Solde initial",
                    ),
                ),
                (
                    "solde_actuel",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Solde actuel",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="Compte par défaut"
                    ),
                ),
                (
                    "date_ouverture",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date d'ouverture",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comptes_bancaires_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comptes_bancaires",
                        to="produits_stocks.warehouse",
                        verbose_name="Entrepôt/Magasin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compte bancaire",
                "verbose_name_plural": "Comptes bancaires",
                "ordering": ["banque", "code"],
                "unique_together": {("warehouse", "code", "numero_compte")},
            },
        ),
        migrations.CreateModel(
            name="MouvementTresorerie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Référence"
                    ),
                ),
                (
                    "type_mouvement",
                    models.CharField(
                        choices=[
                            ("encaissement", "Encaissement"),
                            ("decaissement", "Décaissement"),
                            ("transfert", "Transfert"),
                        ],
                        max_length=20,
                        verbose_name="Type de mouvement",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("vente", "Vente"),
                            ("achat", "Achat"),
                            ("facture_client", "Facture client"),
                            ("facture_fournisseur", "Facture fournisseur"),
                            ("paiement_client", "Paiement client"),
                            ("paiement_fournisseur", "Paiement fournisseur"),
                            ("salaire", "Salaire"),
                            ("frais", "Frais"),
                            ("caisse", "Caisse"),
                            ("compte_bancaire", "Compte bancaire"),
                            ("transfert_interne", "Transfert interne"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type source",
                    ),
                ),
                (
                    "source_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID source"
                    ),
                ),
                (
                    "source_reference",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Référence source",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Montant",
                    ),
                ),
                (
                    "mode_paiement",
                    models.CharField(
                        choices=[
                            ("especes", "Espèces"),
                            ("carte", "Carte bancaire"),
                            ("cheque", "Chèque"),
                            ("virement", "Virement"),
                            ("mobile_money", "Mobile Money"),
                            ("prelevement", "Prélèvement"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Mode de paiement",
                    ),
                ),
                (
                    "date_mouvement",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date du mouvement",
                    ),
                ),
                ("date_valeur", models.DateField(verbose_name="Date de valeur")),
                (
                    "date_prevue",
                    models.DateField(blank=True, null=True, verbose_name="Date prévue"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planifie", "Planifié"),
                            ("en_attente", "En attente"),
                            ("effectue", "Effectué"),
                            ("annule", "Annulé"),
                            ("rejete", "Rejeté"),
                        ],
                        default="planifie",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "reference_externe",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Référence externe",
                    ),
                ),
                (
                    "piece_justificative",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Pièce justificative",
                    ),
                ),
                (
                    "date_rapprochement",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date rapprochement"
                    ),
                ),
                (
                    "rapproche",
                    models.BooleanField(default=False, verbose_name="Rapproché"),
                ),
                ("libelle", models.CharField(max_length=200, verbose_name="Libellé")),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "date_validation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date validation"
                    ),
                ),
                (
                    "caisse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvements",
                        to="tresorerie.caisse",
                        verbose_name="Caisse",
                    ),
                ),
                (
                    "compte_bancaire",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvements",
                        to="tresorerie.comptebancaire",
                        verbose_name="Compte bancaire",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvements_tresorerie_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "facture_vente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvements_tresorerie",
                        to="ventes_clients.facture",
                        verbose_name="Facture vente associée",
                    ),
                ),
                (
                    "paiement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvements_tresorerie",
                        to="ventes_clients.paiement",
                        verbose_name="Paiement associé",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvements_tresorerie",
                        to="achats_fournisseurs.purchaseorder",
                        verbose_name="Commande fournisseur associée",
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvements_tresorerie_valides",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validé par",
                    ),
                ),
                (
                    "vente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvements_tresorerie",
                        to="ventes_clients.vente",
                        verbose_name="Vente associée",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mouvements_tresorerie",
                        to="produits_stocks.warehouse",
                        verbose_name="Entrepôt/Magasin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mouvement de trésorerie",
                "verbose_name_plural": "Mouvements de trésorerie",
                "ordering": ["-date_mouvement"],
            },
        ),
        migrations.CreateModel(
            name="Frais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Référence"
                    ),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("transport", "Transport"),
                            ("restauration", "Restauration"),
                            ("fournitures", "Fournitures de bureau"),
                            ("communication", "Communication"),
                            ("entretien", "Entretien"),
                            ("formation", "Formation"),
                            ("mission", "Mission"),
                            ("representations", "Représentation"),
                            ("assurances", "Assurances"),
                            ("impots", "Impôts et taxes"),
                            ("loyer", "Loyer"),
                            ("services", "Services"),
                            ("fournisseur", "Paiement fournisseur"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Montant",
                    ),
                ),
                (
                    "date_frais",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date du frais"
                    ),
                ),
                (
                    "date_paiement",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de paiement"
                    ),
                ),
                (
                    "beneficiaire",
                    models.CharField(max_length=200, verbose_name="Bénéficiaire"),
                ),
                (
                    "piece_justificative",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Pièce justificative",
                    ),
                ),
                (
                    "mode_paiement",
                    models.CharField(
                        choices=[
                            ("especes", "Espèces"),
                            ("carte", "Carte bancaire"),
                            ("cheque", "Chèque"),
                            ("virement", "Virement"),
                            ("mobile_money", "Mobile Money"),
                            ("prelevement", "Prélèvement"),
                            ("autre", "Autre"),
                        ],
                        default="especes",
                        max_length=20,
                        verbose_name="Mode de paiement",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("en_attente", "En attente de validation"),
                            ("valide", "Validé"),
                            ("paye", "Payé"),
                            ("refuse", "Refusé"),
                            ("annule", "Annulé"),
                        ],
                        default="brouillon",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "date_validation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date validation"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="frais_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="frais",
                        to="achats_fournisseurs.supplier",
                        verbose_name="Fournisseur",
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="frais_valides",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validé par",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="frais",
                        to="produits_stocks.warehouse",
                        verbose_name="Entrepôt/Magasin",
                    ),
                ),
                (
                    "mouvement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="frais_associes",
                        to="tresorerie.mouvementtresorerie",
                        verbose_name="Mouvement associé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Frais",
                "verbose_name_plural": "Frais",
                "ordering": ["-date_frais"],
            },
        ),
        migrations.CreateModel(
            name="PrevisionTresorerie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Référence"
                    ),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "type_prevision",
                    models.CharField(
                        choices=[
                            ("entree", "Entrée prévue"),
                            ("sortie", "Sortie prévue"),
                        ],
                        max_length=20,
                        verbose_name="Type de prévision",
                    ),
                ),
                (
                    "periode",
                    models.CharField(
                        choices=[
                            ("journalier", "Journalier"),
                            ("hebdomadaire", "Hebdomadaire"),
                            ("mensuel", "Mensuel"),
                            ("trimestriel", "Trimestriel"),
                            ("annuel", "Annuel"),
                        ],
                        default="mensuel",
                        max_length=20,
                        verbose_name="Période",
                    ),
                ),
                (
                    "montant_prevu",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Montant prévu",
                    ),
                ),
                (
                    "montant_reel",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Montant réel",
                    ),
                ),
                ("date_debut", models.DateField(verbose_name="Date début")),
                ("date_fin", models.DateField(verbose_name="Date fin")),
                (
                    "source_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Type source"
                    ),
                ),
                (
                    "source_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID source"
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Catégorie"
                    ),
                ),
                (
                    "sous_categorie",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Sous-catégorie",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("en_cours", "En cours"),
                            ("valide", "Validée"),
                            ("realise", "Réalisé"),
                            ("annule", "Annulé"),
                            ("ecart", "Écart constaté"),
                        ],
                        default="brouillon",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "probabilite",
                    models.IntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Probabilité (%)",
                    ),
                ),
                (
                    "ecart",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="Écart"
                    ),
                ),
                (
                    "pourcentage_ecart",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Pourcentage d'écart",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="previsions_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="previsions_tresorerie",
                        to="produits_stocks.warehouse",
                        verbose_name="Entrepôt/Magasin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prévision de trésorerie",
                "verbose_name_plural": "Prévisions de trésorerie",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="RapprochementBancaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Référence"
                    ),
                ),
                ("date_debut", models.DateField(verbose_name="Date début")),
                ("date_fin", models.DateField(verbose_name="Date fin")),
                (
                    "solde_comptable",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Solde comptable",
                    ),
                ),
                (
                    "solde_bancaire",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Solde bancaire",
                    ),
                ),
                (
                    "solde_rapproche",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Solde rapproché",
                    ),
                ),
                (
                    "ecart",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="Écart"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("en_cours", "En cours"),
                            ("partiel", "Partiellement rapproché"),
                            ("complete", "Complètement rapproché"),
                            ("ecart", "Écart constaté"),
                        ],
                        default="brouillon",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "encours_emission",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="En-cours d'émission",
                    ),
                ),
                (
                    "encours_encaissement",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="En-cours d'encaissement",
                    ),
                ),
                (
                    "commissions",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Commissions bancaires",
                    ),
                ),
                (
                    "autres_ecarts",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Autres écarts",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "date_validation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date validation"
                    ),
                ),
                (
                    "compte_bancaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rapprochements",
                        to="tresorerie.comptebancaire",
                        verbose_name="Compte bancaire",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rapprochements_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rapprochements_valides",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validé par",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rapprochements",
                        to="produits_stocks.warehouse",
                        verbose_name="Entrepôt/Magasin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapprochement bancaire",
                "verbose_name_plural": "Rapprochements bancaires",
                "ordering": ["-date_fin"],
            },
        ),
        migrations.CreateModel(
            name="TresorerieJournaliere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                (
                    "solde_ouverture",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Solde d'ouverture",
                    ),
                ),
                (
                    "solde_fermeture",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Solde de fermeture",
                    ),
                ),
                (
                    "total_entrees",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Total entrées",
                    ),
                ),
                (
                    "total_sorties",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Total sorties",
                    ),
                ),
                (
                    "entrees_ventes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Entrées ventes",
                    ),
                ),
                (
                    "entrees_reglements",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Entrées règlements",
                    ),
                ),
                (
                    "entrees_autres",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Entrées autres",
                    ),
                ),
                (
                    "sorties_achats",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Sorties achats",
                    ),
                ),
                (
                    "sorties_frais",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Sorties frais",
                    ),
                ),
                (
                    "sorties_salaires",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Sorties salaires",
                    ),
                ),
                (
                    "sorties_autres",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Sorties autres",
                    ),
                ),
                (
                    "nb_operations",
                    models.IntegerField(default=0, verbose_name="Nombre d'opérations"),
                ),
                (
                    "nb_entrees",
                    models.IntegerField(default=0, verbose_name="Nombre d'entrées"),
                ),
                (
                    "nb_sorties",
                    models.IntegerField(default=0, verbose_name="Nombre de sorties"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tresorerie_journaliere",
                        to="produits_stocks.warehouse",
                        verbose_name="Entrepôt/Magasin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trésorerie journalière",
                "verbose_name_plural": "Trésoreries journalières",
                "ordering": ["-date"],
            },
        ),
        migrations.AddIndex(
            model_name="mouvementtresorerie",
            index=models.Index(
                fields=["reference"], name="tresorerie__referen_98dd07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mouvementtresorerie",
            index=models.Index(
                fields=["type_mouvement", "date_mouvement"],
                name="tresorerie__type_mo_800441_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mouvementtresorerie",
            index=models.Index(
                fields=["warehouse", "status"], name="tresorerie__warehou_a5b40a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mouvementtresorerie",
            index=models.Index(
                fields=["caisse", "date_mouvement"],
                name="tresorerie__caisse__9ce6d1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mouvementtresorerie",
            index=models.Index(
                fields=["compte_bancaire", "date_mouvement"],
                name="tresorerie__compte__9af1c5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mouvementtresorerie",
            index=models.Index(
                fields=["source_type", "source_id"],
                name="tresorerie__source__0c410e_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rapprochementbancaire",
            unique_together={("compte_bancaire", "date_debut", "date_fin")},
        ),
        migrations.AlterUniqueTogether(
            name="tresoreriejournaliere",
            unique_together={("date", "warehouse")},
        ),
    ]
